Feature/button
michalszc/SimpleUI pull request #3
Opened 2023-02-15 18:02 UTC by kingawr123

- Basic Button component 
- some test
- storybook

2023-02-15 20:06 UTC, michalszc requested changes

2023-02-15 20:06 UTC, michalszc commented on tests/components/Button.test.tsx
> +    expect(onClick).toHaveBeenCalledTimes(0);
Replace with .not.toBeCalled()

2023-02-15 20:06 UTC, michalszc commented on stories/components/Button.stories.tsx
> +
Maybe without this empty line?

2023-02-15 20:06 UTC, michalszc commented on stories/components/Button.stories.tsx
> +const Template: ComponentStory<typeof Button> = (args) => <Button {...args}/>;
```suggestion
const Template: ComponentStory<typeof Button> = (args) => <Button {...args} />;
```

2023-02-15 22:23 UTC, kingawr123 reviewed
i've made the requested changes

2023-02-16 17:38 UTC, michalszc requested changes

2023-02-16 17:38 UTC, michalszc commented on package.json
> +  "version": "0.1.0",
```suggestion
  "version": "0.2.0",
```

2023-02-16 18:43 UTC, michalszc approved these changes

2023-02-16 19:59 UTC, merged